### PR TITLE
Add comment

### PR DESCRIPTION
**Pull request by Validark**
Add a line of documentation

### CODE REVIEW

**Review by Quenty — CHANGES_REQUESTED** [review]
This change makes it harder to read with no obvious performance benefits. In my opinion, asserts are better than if statements in this case, especially if you aren't formatting strings inside of the assert.

**Comment by Quenty** [comment]
The comment is good!

**Comment by Validark** [comment]
xD

**Comment by Validark** [comment]
@Quenty Would you use this module?

**Comment by Quenty** [comment]
Looks like it may be useful, but not something I plan on immediately incorporating.

**Pull request merged**
